server:
  port: 10003
  servlet:
    context-path: /store
spring:
#  application:
#    name: user-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+08:00
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelligent_store?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
  # jpa
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true
  # 发邮件
  mail:
    host: smtp.qq.com              #发送邮件服务器
    username: 1647835111@qq.com    #发送邮件的邮箱地址
    password: htxxfudwswlxdfha     #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    protocol: smtp
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.auth: true
    from: 1647835111@qq.com        # 发送邮件的地址，和上面username一致可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true